name: MengXiOS-build-test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: build-test
      run: |
        bash build.sh