name: MengXiOS-build-test
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: build-test
      run: |
        echo $USER
        bash build.sh