name: MengXiOS-build-test
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: install-depend
      run: bash depend.sh

    - name: pre-build
      run: bash build.sh
  
    - name: file-list
      run: tree

    - name: pack-binary
      run: tar cjvf mxde.tbz mxde

    - name: iso
      run: bash auto.sh

    - name: upload-binary
      uses: actions/upload-artifact@v3
      with:
        name: mxde
        path: mxde.tbz
        if-no-files-found: error
        retention-days: 30