name: MengXiOS-build-test
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: build-test
      run: |
        echo $USER
        bash build.sh

    - name: upload-iso
      uses: actions/upload-artifact@v3
      with:
        name: mxos
        path: ~/*.iso
        if-no-files-found: error
        retention-days: 30