name: MengXiOS-build-test
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: install-depend
      run: bash depend.sh

    - name: build-test
      run: bash build.sh

    - name: build-iso
      run: bash make-iso.sh
   
    - name: list&pack
      run: tree && tar cjf mxde.tbz mxde

    - name: upload-iso
      uses: actions/upload-artifact@v3
      with:
        name: mxos
        path: /home/runner/work/mx-os-build-script/mx-os-build-script/*.iso
        if-no-files-found: error
        retention-days: 30