name: MengXiOS-build-test
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: install-depend
      run: bash depend.sh

    - name: build-test
      run: bash build.sh
  
    - name: list&pack
      run: tree

    - name: upload-binary
      uses: actions/upload-artifact@v3
      with:
        name: mxde
        path: mxde
        if-no-files-found: error
        retention-days: 30